// ~~ Generated by projen. To modify, edit .projenrc.ts and run "yarn projen".
// @ts-check
/** @type {import('@yarnpkg/types')} */
const { defineConfig } = require(`@yarnpkg/types`);

module.exports = defineConfig({
  async constraints({ Yarn }) {
    const root = Yarn.workspace({ cwd: '.' });
    for (const ident of ["nx"]) {
      const expected = root.manifest.devDependencies?.[ident];
      if (!expected) continue;
      for (const workspace of Yarn.workspaces()) {
        if (workspace.manifest.devDependencies?.[ident]) {
          workspace.set(['devDependencies', ident], expected);
        }
      }
    }
  },
});
